### PR TITLE
Fixed 4 lines lyrics sync with timestamp

### PR DESCRIPTION
**Pull request by lecheel**
qt
gtk

### CODE REVIEW

**Comment by lecheel** [comment]
forgot the qt version changed

**Review by lecheel — COMMENTED** [review]
fixed both gtk and qt

**Comment by wildstar84** [comment]
Thank you for your code contribution!  I've given it a quick test and have 3 issues so far:
1)  Does not work, at least for lyrics files that do not contain timestamps:  Lyrics display for a fraction of a second when starting playback, but are immediately blanked out/cleared.
2)  Can you provide me a sample song file and corresponding lyrics file with timestamps to test / work with?
3)  There should be a lyrics-plugin config option checkbox to enable this new feature (not all users may want it)  Default should be unchecked(disabled) and require user to enable.
That's all I've got for now.  Address these issues and we'll go from there.  This sounds like a good feature for Fauxdacious & I look forward to merging it when we get it working properly, though I reserve the right to tweak it a bit if needed.  I will also credit you for the feature where applicable in docs/notes/changelog!

**Comment by lecheel** [comment]
[old_radio.zip](https://github.com/user-attachments/files/17891798/old_radio.zip)
that's right I forgot the handle the lrc without timestamp, add checkbox should be great

**Comment by lecheel** [comment]
did you try old_radio.zip song with lyrics work for u

**Comment by wildstar84** [comment]
Thanks for your sample timestamped lyric file!  I've used it to test with & found & fixed several issues:
1)  I've modified the timer to only run when the new sync. option is on *and* valied timestamped lyrics are found & used (This saves some wasted CPU cycles, etc.)
2)  Most of the other issues were related to handling the [Save] & [Embed] options, namely that they must be greyed out whenever doing lyric-sync (otherwise a user's saved lyrics file will be overwirtten with just the 3 sentences of lyrics currently on the screen)!
3)  A few misc. code cleanups & to conform with our (originally Audacious's) code-formatting conventions.  I'm attaching the modified files along with corresponding ".diff"s showing what I changed (though you'll likely wish to use a graphical diff to compare side-by-side).
4)  I added an "About" popup for both versions that includes crediting you for the added feature as "lecheel", since I do not have your given name.  I can change it to your name (need your name), or if you'd prefer I can leave it as-is; or remove your credit if you'd prefer anonimity.

I went ahead and left the new sync option defaulted as TRUE despite my misgivings because apparently the "Search the Web" option is currently also defaulted to TRUE & I didn't want to change it, & having them different didn't make much sense.

Please test more of your timestamped files (& perhaps some others) & let me know, so we can either make further adjustments and/or merge this in soon!

I also found this article about timestamped LRC files that you might find interesting.  There were a cpl. other things you might find an interest in adding to what we've done so far in your spare time.  If so, feed free to submit any of that here for merging consideration!

Regards,

Jim

**Comment by lecheel** [comment]
Thank you, Jim. I'm glad the timestamped sync LRC is now working effectively. While there are still several areas that could be improved, your changes definitely optimize CPU usage much better. For the sample LRC file I used
[whisper auto lrc creater](https://github.com/lecheel/lrc_maker) auto generate, it seems that multi timestamp is not supported yet. will revisit to have better lrc support.    Walaoke  is a cool feature but no song lrc can not founded.

**Comment by wildstar84** [comment]
Please test several other timestamped songs & let me know if you run into any bugs, or that all is well so I can merge(commit) the changes I sent to you as-is into mainline Fauxdacious!  Your "whisper" thing looks interesting, but I don't have Python 3.8, etc. & can't currently update this system, so I'm not going to be able to use it for now.

**Comment by lecheel** [comment]
so way without any problem for most lrc with [ti],[at],[al] tags the only problem old multi-timestamp tag will show like this
[00:01.00][00:05.00] line1
line2 
[00:02.00][00:10.00][00:20.00]line3

**Comment by lecheel** [comment]
There is a segmentation fault if you continue playing music without stopping it before closing the app.

**Comment by lecheel** [comment]
It's great to hear that you were able to quickly resolve the issue :-), yes GTK without have such problem everything is working well

**Comment by wildstar84** [comment]
This pull-request has now been committed.  Thanks again!

Jim

**Pull request closed without merging**
